Repository ignission/jam, pull requests merged in 2021-05, with the labels that each got.

#85 Fix user name is always same
  jam-client/src/App.tsx
  jam-client/src/components/pages/Lobby.tsx
Labels: bug

#88 Reborn GitHub Actions
  .github/workflows/CI.yml
  .github/workflows/release-drafter.yml
  .github_/release-drafter.yml
  .github_/workflows/Build.yml
  .github_/workflows/docker-image-http.yml
  .github_/workflows/docker-image-websocket.yml
  README.md
Labels: chore

#89 Dockerize
  .github/workflows/Build.yml
  .gitignore
  build.sbt
  jam-client/package.json
  jam-client/src/components/pages/Lobby.tsx
  jam-client/src/types/variables.d.ts
  jam-client/webpack.common.js
  jam-client/webpack.local.js
  jam-client/webpack.prod.js
  jam-server/app/controllers/AssetController.scala
  jam-server/conf/application.conf
  jam-server/conf/docker.conf
  jam-server/conf/routes
  project/plugins.sbt
Labels: chore

#90 Control the chat balloon
  jam-client/src/components/molecules/User.tsx
  jam-client/src/components/pages/Lobby.tsx
Labels: enhancement

#91 Prevent moving when typing
  jam-client/src/components/molecules/User.tsx
  jam-client/src/components/pages/Lobby.tsx
Labels: bug

#94 Setup openvidu docker
  docker-compose.dev.yml
  docker-compose.yml
  project/DockerComposeRunHook.scala
Labels: chore

#95 Setup openvidu
  build.sbt
  jam-server/conf/application.conf
  jam-server/conf/docker.conf
Labels: chore

#96 Refactoring lobby
  jam-client/src/components/atoms/Balloon.tsx
  jam-client/src/components/atoms/index.ts
  jam-client/src/components/molecules/ChatBalloon.tsx
  jam-client/src/components/molecules/Myself.tsx
  jam-client/src/components/molecules/Participant.tsx
  jam-client/src/components/molecules/index.ts
  jam-client/src/components/pages/Lobby.tsx
  jam-client/src/models/Position.ts
Labels: chore
